name = "investmtl-api"
main = "src/index.ts"
compatibility_date = "2023-12-01"

# Variables (these will be set via dashboard or CLI)
[vars]
API_VERSION = "1.0.0"
CORS_ORIGINS = "*"
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "60"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "investmtl-db"
database_id = "737f69f1-cc9c-4822-99e4-fe71a6377f99"

# KV Namespace binding
[[kv_namespaces]]
binding = "KV"
id = "b7c3c11966044deab589860400ee320c"
# preview_id = "your-preview-kv-namespace-id"

# Analytics Engine binding (optional)
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"

# Environment-specific configurations
[env.production]
name = "investmtl-api-prod"

[env.staging]  
name = "investmtl-api-staging"
